name: gofamily
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3

  # ---- RIVERPOD ----
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  # ---- WEATHER / API ----
  http: ^1.1.0

  # ---- LOCATION (GPS) ----
  geolocator: ^10.0.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # ---- ICONS ----
  flutter_launcher_icons: ^0.13.1

  # ---- CODE GENERATOR (RIVERPOD) ----
  build_runner: ^2.4.9
  riverpod_generator: ^3.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/logo/app_logo.png
    - assets/icons/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
